# --- Configuration ---
DB_PATH = "output/reddit_ideas.db"

SUBREDDITS = [
    # "alphaandbetausers",
    # "AppIdeas",
    # "AndroidApps",
    # "Entrepreneur",
    # "FlutterDev",
    # "iOSProgramming",
    # "MobileDev",
    # "nocode",
    "microsaas",
    # "reactnative",
    "SaaS",
    "SideProject",
    # "SomebodyMakeThis",
    # "startup",
    # "StartupIdeas",
    # "sveltejs",
    "SvelteKit",
    "webdev",
]
KEYWORDS = [
    # "an app that",
    # "business",
    # "app idea",
    # "app for",
    # "app that helps with",
    # "app to automate",
    # "app to track",
    # "app to manage",
    # "app to connect",
    # "app to simplify",
    # "app to organize",
    # "app to improve",
    # "app to monitor",
    # "app to reduce",
    # "app to enhance",
    # "app to find",
    # "app to compare",
    # "app to share",
    # "app to learn",
    # "app to earn",
    # "app to save",
    # "app to solve",
    # "app to discover",
    # "app to schedule",
    # "app to remind",
    # "app to analyze",
    # "app to visualize",
    # "app to collaborate",
    # "app to customize",
    # "app to gamify",
    # "app to streamline",
    # "app to integrate",
    # "app to optimize",
    # "app to personalize",
    # "app to measure",
    # "great idea",
    # "I need an app",
    # "I wish there was",
    # "is there an app for",
    "making money",
    "microsaas",
    "saas",
    "side project",
    # "someone should build",
    # "startup",
    "svelte",
    # "why isn't there an app for",
]
