# --- Configuration ---
DB_PATH = "output/reddit_ideas.db"

# --- Step 2: Configuration ---
SUBREDDITS = [
    "AppIdeas",
    # "AndroidApps",
    # "iOSProgramming",
    # "StartupIdeas",
    # "FlutterDev",
    # "SaaS",
    # "nocode",
    # "microsaas",
    # "reactnative",
    # "sveltejs",
    # "SvelteKit",
    # "startup",
    # "alphaandbetausers",
    # "MobileDev",
    "SomebodyMakeThis",
    "Entrepreneur",
    "SideProject",
]
KEYWORDS = [
    "I wish there was an app for",
    # "an app that",
    # "app idea",
    # "someone should build",
    # "I need an app",
    # "is there an app for",
    # "app to solve",
    # "app for",
    "why isn't there an app for",
    "app that helps with",
    "app to automate",
    # "app to track",
    # "app to manage",
    # "app to connect",
    # "app to simplify",
    # "app to organize",
    # "app to improve",
    # "app to monitor",
    # "app to reduce",
    # "app to enhance",
    # "app to find",
    # "app to compare",
    # "app to share",
    # "app to learn",
    # "app to earn",
    # "app to save",
    # "app to discover",
    # "app to schedule",
    # "app to remind",
    # "app to analyze",
    # "app to visualize",
    # "app to collaborate",
    # "app to customize",
    # "app to gamify",
    # "app to streamline",
    # "app to integrate",
    # "app to optimize",
    # "app to personalize",
    # "app to measure",
]
